name: update-release-draft

on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-release-draft:
    name: Update release draft
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        with:
          config-name: release-drafter.yaml
