# Generated by Django 4.1.4 on 2022-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warga",
            name="agama",
            field=models.CharField(
                choices=[
                    ("islam", "ISLAM"),
                    ("kristen katholik", "KATHOLIK"),
                    ("kristen protestan", "KRISTEN"),
                    ("hindu", "HINDU"),
                    ("buddha", "BUDDHA"),
                    ("konghucu", "KONGHUCU"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="warga",
            name="jenis_kelamin",
            field=models.CharField(
                choices=[
                    ("islam", "ISLAM"),
                    ("kristen katholik", "KATHOLIK"),
                    ("kristen protestan", "KRISTEN"),
                    ("hindu", "HINDU"),
                    ("buddha", "BUDDHA"),
                    ("konghucu", "KONGHUCU"),
                ],
                default="Perempuan",
                max_length=30,
            ),
        ),
    ]
