# Generated by Django 4.1.4 on 2022-12-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0002_alter_warga_agama_alter_warga_jenis_kelamin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warga",
            name="jenis_kelamin",
            field=models.CharField(
                choices=[("Laki-laki", "laki-laki"), ("Perempuan", "perempuan")],
                default="Perempuan",
                max_length=30,
            ),
        ),
    ]
