# Generated by Django 4.1.4 on 2022-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0003_alter_warga_jenis_kelamin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warga",
            name="nik",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
