# Generated by Django 4.1.4 on 2022-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0004_alter_warga_nik"),
    ]

    operations = [
        migrations.AddField(
            model_name="warga",
            name="alamat_blok",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="warga",
            name="alamat_nomor",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="warga",
            name="status_tinggal",
            field=models.CharField(
                choices=[
                    ("KONTRAK", "KONTRAK"),
                    ("KOST", "KOST"),
                    ("TETAP", "TETAP"),
                    ("PINDAH", "PINDAH"),
                    ("LAINNYA", "LAINNYA"),
                ],
                default="TETAP",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="warga",
            name="pekerjaan",
            field=models.CharField(
                choices=[
                    ("PELAJAR/MAHASISWA", "PELAJAR/MAHASISWA"),
                    ("PNS", "PNS"),
                    ("KARYAWAN SWASTA", "KARYAWAN SWASTA"),
                    ("KARYAWAN BUMN", "KARYAWAN BUMN"),
                    ("TNI", "TNI"),
                    ("POLRI", "POLRI"),
                    ("NAKES", "NAKES"),
                    ("WIRASWASTA", "WIRASWASTA"),
                    ("MENGURUS RUMAH TANGGA", "MENGURUS RUMAH TANGGA"),
                    ("GURU", "GURU"),
                    ("OJEK", "OJEK"),
                    ("LAINNYA", "LAINNYA"),
                ],
                default="KARYAWAN SWASTA",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="warga",
            name="rt",
            field=models.CharField(default="006", max_length=4),
        ),
        migrations.AlterField(
            model_name="warga",
            name="rw",
            field=models.CharField(default="012", max_length=4),
        ),
        migrations.AlterField(
            model_name="warga",
            name="status",
            field=models.CharField(
                choices=[
                    ("BELUM KAWIN", "BELUM KAWIN"),
                    ("KAWIN", "KAWIN"),
                    ("CERAI HIDUP", "CERAI HIDUP"),
                    ("CERAI MATI", "CERAI MATI"),
                ],
                default="BELUM KAWIN",
                max_length=50,
            ),
        ),
    ]
