# Generated by Django 4.1.4 on 2022-12-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0006_alter_warga_alamat"),
    ]

    operations = [
        migrations.AddField(
            model_name="warga",
            name="alamat_ktp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
