# Generated by Django 4.1.4 on 2023-01-16 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0010_alter_warga_alamat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warga",
            name="alamat_blok",
        ),
        migrations.RemoveField(
            model_name="warga",
            name="alamat_nomor",
        ),
    ]
