# Generated by Django 4.1.4 on 2023-01-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0011_remove_warga_alamat_blok_remove_warga_alamat_nomor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warga",
            name="rt",
        ),
        migrations.RemoveField(
            model_name="warga",
            name="rw",
        ),
    ]
