# Generated by Django 4.1.4 on 2023-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0013_remove_warga_alamat_remove_warga_kecamatan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warga",
            name="agama",
            field=models.CharField(
                choices=[
                    ("ISLAM", "ISLAM"),
                    ("KATHOLIK", "KATHOLIK"),
                    ("KRISTEN", "KRISTEN"),
                    ("HINDU", "HINDU"),
                    ("BUDDHA", "BUDDHA"),
                    ("KONGHUCU", "KONGHUCU"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="warga",
            name="jenis_kelamin",
            field=models.CharField(
                choices=[("LAKI-LAKI", "LAKI-LAKI"), ("PEREMPUAN", "PEREMPUAN")],
                default="Perempuan",
                max_length=30,
            ),
        ),
    ]
