# Generated by Django 4.1.4 on 2023-02-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0014_alter_warga_agama_alter_warga_jenis_kelamin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warga",
            name="no_hp",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
