# Generated by Django 4.1.4 on 2023-02-28 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0015_alter_warga_no_hp_transaksiiuranbulanan"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransaksiIuranBulanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_bayar", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("keterangan", models.TextField(blank=True, null=True)),
                ("bukti_bayar", models.FileField(blank=True, upload_to="bukti_bayar")),
                (
                    "periode_bulan",
                    models.CharField(
                        choices=[
                            ("1", "Januari"),
                            ("2", "Februari"),
                            ("3", "Maret"),
                            ("4", "April"),
                            ("5", "Mei"),
                            ("6", "Juni"),
                            ("7", "Juli"),
                            ("8", "Agustus"),
                            ("9", "September"),
                            ("10", "Oktober"),
                            ("11", "November"),
                            ("12", "Desember"),
                        ],
                        max_length=30,
                    ),
                ),
                ("periode_tahun", models.IntegerField()),
                ("total_bayar", models.IntegerField(default=150000)),
                (
                    "kompleks",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kependudukan.kompleks",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="transaksiiuranbulanan",
            index=models.Index(
                fields=["periode_bulan"], name="kependuduka_periode_d75dca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaksiiuranbulanan",
            index=models.Index(
                fields=["periode_tahun"], name="kependuduka_periode_b69792_idx"
            ),
        ),
    ]
