# Generated by Django 4.1.4 on 2023-02-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0016_alter_transaksiiuranbulanan_bukti_bayar_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaksiiuranbulanan",
            old_name="timestamp_transaksi",
            new_name="last_modified",
        ),
    ]
