# Generated by Django 4.1.4 on 2023-03-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0017_alter_transaksiiuranbulanan_bukti_bayar"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="kompleks",
            index=models.Index(fields=["blok"], name="kependuduka_blok_2c7004_idx"),
        ),
        migrations.AddIndex(
            model_name="kompleks",
            index=models.Index(fields=["nomor"], name="kependuduka_nomor_c39faa_idx"),
        ),
        migrations.AddIndex(
            model_name="kompleks",
            index=models.Index(
                fields=["cluster"], name="kependuduka_cluster_5c3fd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warga",
            index=models.Index(
                fields=["nama_lengkap"], name="kependuduka_nama_le_08a3b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warga",
            index=models.Index(fields=["nik"], name="kependuduka_nik_fba900_idx"),
        ),
        migrations.AddIndex(
            model_name="warga",
            index=models.Index(fields=["no_kk"], name="kependuduka_no_kk_5c5a0a_idx"),
        ),
        migrations.AddIndex(
            model_name="warga",
            index=models.Index(fields=["agama"], name="kependuduka_agama_7a8877_idx"),
        ),
        migrations.AddIndex(
            model_name="warga",
            index=models.Index(
                fields=["jenis_kelamin"], name="kependuduka_jenis_k_385e3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warga",
            index=models.Index(
                fields=["status_tinggal"], name="kependuduka_status__006096_idx"
            ),
        ),
    ]
