# Generated by Django 4.1.4 on 2023-04-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0019_warga_status_keluarga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaksiiuranbulanan",
            name="periode_bulan",
            field=models.IntegerField(
                choices=[
                    ("1", "Januari"),
                    ("2", "Februari"),
                    ("3", "Maret"),
                    ("4", "April"),
                    ("5", "Mei"),
                    ("6", "Juni"),
                    ("7", "Juli"),
                    ("8", "Agustus"),
                    ("9", "September"),
                    ("10", "Oktober"),
                    ("11", "November"),
                    ("12", "Desember"),
                ]
            ),
        ),
    ]
