# Generated by Django 4.1.4 on 2023-04-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0020_alter_transaksiiuranbulanan_periode_bulan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaksiiuranbulanan",
            name="periode_bulan",
            field=models.IntegerField(
                choices=[
                    (1, "Januari"),
                    (2, "Februari"),
                    (3, "Maret"),
                    (4, "April"),
                    (5, "Mei"),
                    (6, "Juni"),
                    (7, "Juli"),
                    (8, "Agustus"),
                    (9, "September"),
                    (10, "Oktober"),
                    (11, "November"),
                    (12, "Desember"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="SummaryTransaksiBulanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode_tahun", models.IntegerField()),
                ("january", models.BooleanField()),
                ("february", models.BooleanField()),
                ("march", models.BooleanField()),
                ("april", models.BooleanField()),
                ("may", models.BooleanField()),
                ("june", models.BooleanField()),
                ("july", models.BooleanField()),
                ("august", models.BooleanField()),
                ("september", models.BooleanField()),
                ("october", models.BooleanField()),
                ("november", models.BooleanField()),
                ("december", models.BooleanField()),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "kompleks",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kependudukan.kompleks",
                    ),
                ),
            ],
        ),
    ]
