# Generated by Django 6.0.5 on 2026-05-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0025_wargapermissiongroup_userpermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warga",
            name="ktp_image_path",
            field=models.ImageField(blank=True, upload_to="uploads/"),
        ),
    ]
