# Generated by Django 6.0.5 on 2026-05-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0026_warga_ktp_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warga",
            name="status_tinggal",
            field=models.CharField(
                choices=[
                    ("KONTRAK", "KONTRAK"),
                    ("KOST", "KOST"),
                    ("TETAP", "TETAP"),
                    ("PINDAH", "PINDAH"),
                    ("MENINGGAL", "MENINGGAL"),
                    ("LAINNYA", "LAINNYA"),
                ],
                default="TETAP",
                max_length=30,
            ),
        ),
    ]
