# Generated by Django 6.0.5 on 2026-05-22 03:11

import datetime
import django.db.models.deletion
import kependudukan.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0029_kendaraan"),
    ]

    operations = [
        migrations.CreateModel(
            name="KasTagihan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("PIUTANG", "Piutang (Receivable)"),
                            ("HUTANG", "Hutang (Payable)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("IURAN", "Iuran Bulanan"),
                            ("SOSIAL", "Sosial/Sumbangan"),
                            ("KEBERSIHAN", "Kebersihan"),
                            ("KEAMANAN", "Keamanan"),
                            ("OPERASIONAL", "Operasional"),
                            ("PEMBANGUNAN", "Pembangunan/Infrastruktur"),
                            ("LAINNYA", "Lain-lain"),
                        ],
                        default="LAINNYA",
                        max_length=30,
                    ),
                ),
                ("jumlah", models.IntegerField()),
                ("tanggal_jatuh_tempo", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("BELUM", "Belum Bayar"), ("LUNAS", "Lunas")],
                        default="BELUM",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True, null=True)),
                ("tanggal_dibuat", models.DateField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tanggal_jatuh_tempo"],
                        name="kependuduka_tanggal_055557_idx",
                    ),
                    models.Index(fields=["jenis"], name="kependuduka_jenis_355ac5_idx"),
                    models.Index(
                        fields=["kategori"], name="kependuduka_kategor_f0ea6a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="kependuduka_status_7ffd7c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KasTransaksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(default=datetime.date.today)),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("PEMASUKAN", "Pemasukan"),
                            ("PENGELUARAN", "Pengeluaran"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("IURAN", "Iuran Bulanan"),
                            ("SOSIAL", "Sosial/Sumbangan"),
                            ("KEBERSIHAN", "Kebersihan"),
                            ("KEAMANAN", "Keamanan"),
                            ("OPERASIONAL", "Operasional"),
                            ("PEMBANGUNAN", "Pembangunan/Infrastruktur"),
                            ("LAINNYA", "Lain-lain"),
                        ],
                        default="LAINNYA",
                        max_length=30,
                    ),
                ),
                ("jumlah", models.IntegerField()),
                ("keterangan", models.TextField(blank=True, null=True)),
                (
                    "bukti_transaksi",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=kependudukan.models.upload_kas_to,
                    ),
                ),
                (
                    "iuran_asal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kas_transaksi",
                        to="kependudukan.transaksiiuranbulanan",
                    ),
                ),
                (
                    "tagihan_asal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pembayaran",
                        to="kependudukan.kastagihan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tanggal"], name="kependuduka_tanggal_b994fc_idx"
                    ),
                    models.Index(fields=["jenis"], name="kependuduka_jenis_cc5910_idx"),
                    models.Index(
                        fields=["kategori"], name="kependuduka_kategor_257b47_idx"
                    ),
                ],
            },
        ),
    ]
