# Generated by Django 6.0.5 on 2026-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0031_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_permanently_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="shadow_ban_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
