# Generated by Django 6.0.5 on 2026-05-27 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kependudukan", "0034_userinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kendaraan",
            name="keterangan_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kendaraan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Menunggu Persetujuan"),
                    ("APPROVED", "Disetujui"),
                    ("REJECTED", "Ditolak"),
                ],
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="surat",
            name="keterangan_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surat",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Menunggu Persetujuan"),
                    ("APPROVED", "Disetujui"),
                    ("REJECTED", "Ditolak"),
                ],
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaksiiuranbulanan",
            name="keterangan_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaksiiuranbulanan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Menunggu Persetujuan"),
                    ("APPROVED", "Disetujui"),
                    ("REJECTED", "Ditolak"),
                ],
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="warga",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warga",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="WargaUpdateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_changes", models.JSONField(default=dict)),
                (
                    "foto_path",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/updates/"
                    ),
                ),
                (
                    "ktp_image_path",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/updates/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Menunggu Persetujuan"),
                            ("APPROVED", "Disetujui"),
                            ("REJECTED", "Ditolak"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_requests",
                        to="kependudukan.warga",
                    ),
                ),
            ],
        ),
    ]
