# Generated by Django 6.0.5 on 2026-05-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kependudukan", "0035_kendaraan_keterangan_status_kendaraan_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wargaupdaterequest",
            name="is_new_warga",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wargaupdaterequest",
            name="kompleks",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kependudukan.kompleks",
            ),
        ),
        migrations.AddField(
            model_name="wargaupdaterequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_update_requests",
                to="kependudukan.warga",
            ),
        ),
        migrations.AlterField(
            model_name="wargaupdaterequest",
            name="warga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_requests",
                to="kependudukan.warga",
            ),
        ),
    ]
